#Implement Gradient Descent For Neural Network (or Logistic Regression)

In [ ]:
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import numpy as np



In [ ]:
data = pd.read_csv('/content/drive/MyDrive/DL notebooks/titanic.csv')



## scaling data and create a fetures and targets variables

In [ ]:
x = data[['Pclass', 'Age', 'Sex']].copy()
y = data[['Survived']].values.flatten()

x['n_age'] = x['Age'].fillna(x['Age'].mean())
x['N_Sex'] = x['Sex'].apply(lambda x: 1 if x == 'male' else 0)
x.drop(["Sex", "Age"], axis=1, inplace=True)

scaler = StandardScaler()
x = scaler.fit_transform(x)



In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.1, random_state=42)

In [ ]:
x_train

array([[ 0.82737724, -1.59288716,  0.73769513],
       [ 0.82737724, -1.59288716, -1.35557354],
       [-1.56610693,  2.40873908,  0.73769513],
       ...,
       [ 0.82737724,  0.86965206,  0.73769513],
       [-1.56610693, -1.20811541, -1.35557354],
       [-1.56610693, -0.66943495,  0.73769513]])

##training model using logistic regresion(sigmoid)


In [ ]:

model = keras.Sequential([
    keras.layers.Dense(1, input_shape=(3,), activation='sigmoid')
])

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)
model.fit(x_train,y_train,epochs=100)

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - accuracy: 0.7201 - loss: 0.5622
Epoch 2/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7462 - loss: 0.5518
Epoch 3/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7276 - loss: 0.5506
Epoch 4/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7500 - loss: 0.5453 
Epoch 5/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7502 - loss: 0.5332 
Epoch 6/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7662 - loss: 0.5182 
Epoch 7/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7587 - loss: 0.5303 
Epoch 8/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7902 - loss: 0.5018 
Epoch 9/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7655 - loss: 0.5204 
Epoch 10/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7502 - loss: 0.5227 
Epoch 11/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7713 - loss: 0.5186 
Epoch 12/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - 

##Watching loss which near to in between  4.3 to 4.80

In [ ]:
model.evaluate(x_test,y_test)

3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.8457 - loss: 0.3991


[0.3844362795352936, 0.855555534362793]

In [ ]:
coef, intercept = model.get_weights()
coef,intercept

(array([[-0.87819064],
        [-0.33768994],
        [-1.1709281 ]], dtype=float32),
 array([-0.58027995], dtype=float32))

In [ ]:
y_test

array([1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0])

In [ ]:
model.predict(x_test)

3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step 


array([[0.10241608],
       [0.23985022],
       [0.12801611],
       [0.8751447 ],
       [0.6656048 ],
       [0.9226185 ],
       [0.56964535],
       [0.14007491],
       [0.65393907],
       [0.9346476 ],
       [0.43574396],
       [0.07294576],
       [0.56964535],
       [0.10169952],
       [0.21696618],
       [0.9392512 ],
       [0.40410566],
       [0.56964535],
       [0.25931075],
       [0.37324506],
       [0.11685437],
       [0.4549988 ],
       [0.6360913 ],
       [0.12801611],
       [0.10241608],
       [0.15993018],
       [0.41668096],
       [0.23985022],
       [0.1820042 ],
       [0.56133914],
       [0.1309451 ],
       [0.617861  ],
       [0.48282486],
       [0.56964535],
       [0.13393082],
       [0.10904614],
       [0.49385703],
       [0.56964535],
       [0.91486365],
       [0.10241608],
       [0.2903605 ],
       [0.10409828],
       [0.10241608],
       [0.10241608],
       [0.47072968],
       [0.14007491],
       [0.1309451 ],
       [0.119

In [ ]:
import math
def sigmoid(x):
  return 1 / (1+math.exp(-x))


In [ ]:
x_test_df = pd.DataFrame(x_test)
x_test_df.head()

0         1         2
0  0.827377  0.000000  0.737695
1 -0.369365  0.100109  0.737695
2  0.827377 -0.746389  0.737695
3 -0.369365 -1.823750 -1.355574
4  0.827377 -1.208115 -1.355574

##creating a prediction fucntion from python scratchs

In [ ]:
from re import A
def prediction_func(Pclass,Age,Sex):
  weighted_sum = coef[0]*Pclass + coef[1]*Age + coef[2]*Sex + intercept
  return sigmoid(weighted_sum)

prediction_func(-0.369365	,-1.823750,-1.355574)

<ipython-input-16-837c0ec799d8>:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1 / (1+math.exp(-x))


0.8751447802045583

In [ ]:
def sigmoid_numpy(x):
  return 1 / (1+np.exp(-x))

sigmoid_numpy(np.array([-0.369365,-1.823750,-1.355574]))


array([0.40869447, 0.13898451, 0.20496058])

In [ ]:
def log_loss(y_true, y_predicted):
    epsilon = 1e-15
    y_predicted_new = np.clip(y_predicted, epsilon, 1 - epsilon)
    return -np.mean(y_true * np.log(y_predicted_new) + (1 - y_true) * np.log(1 - y_predicted_new))


#Gradieant decent from python scratch

In [ ]:
def gradient_Decent(Pclass,Age,Sex,y_true, epochs, loss_threshold):
  w1 = w2 = w3 = 1
  bias = 0
  rate = 0.5
  n = len(Pclass)
  for i in range(epochs):
     weighted_sum = w1*Pclass + w2*Age + w3*Sex + bias
     y_predicted = sigmoid_numpy(weighted_sum)
     loss = log_loss(y_true, y_predicted)
     w1d = (1 / n) * np.dot(Pclass, (y_predicted - y_true))
     w2d = (1 / n) * np.dot(Age, (y_predicted - y_true))
     w3d = (1 / n) * np.dot(Sex, (y_predicted - y_true))
     bias_d = np.mean(y_predicted - y_true)
     w1 = w1 - rate * w1d
     w2 = w2 - rate * w2d
     w3 = w3 - rate * w3d
     bias = bias - rate * bias_d

     print(f"Epoch {i + 1}: w1={w1:.4f}, w2={w2:.4f}, w3={w3:.4f}, bias={bias:.4f}, loss={loss:.4f}")


     if loss <= loss_threshold:
      break
  return w1,w2,bias

In [ ]:
gradient_Decent(x_train[:,0],x_train[:,1],x_train[:,2],y_train,100,0.4568)

Epoch 1: w1=0.8512, w2=0.9246, w3=0.7592, bias=-0.0679, loss=1.4248
Epoch 2: w1=0.7112, w2=0.8472, w3=0.5375, bias=-0.1271, loss=1.2502
Epoch 3: w1=0.5816, w2=0.7692, w3=0.3360, bias=-0.1778, loss=1.0999
Epoch 4: w1=0.4630, w2=0.6921, w3=0.1552, bias=-0.2206, loss=0.9737
Epoch 5: w1=0.3558, w2=0.6176, w3=-0.0050, bias=-0.2566, loss=0.8701
Epoch 6: w1=0.2594, w2=0.5469, w3=-0.1456, bias=-0.2868, loss=0.7868
Epoch 7: w1=0.1731, w2=0.4809, w3=-0.2680, bias=-0.3126, loss=0.7209
Epoch 8: w1=0.0960, w2=0.4202, w3=-0.3742, bias=-0.3347, loss=0.6692
Epoch 9: w1=0.0269, w2=0.3649, w3=-0.4660, bias=-0.3540, loss=0.6289
Epoch 10: w1=-0.0353, w2=0.3147, w3=-0.5455, bias=-0.3710, loss=0.5976
Epoch 11: w1=-0.0914, w2=0.2693, w3=-0.6142, bias=-0.3863, loss=0.5731
Epoch 12: w1=-0.1424, w2=0.2282, w3=-0.6740, bias=-0.4000, loss=0.5539
Epoch 13: w1=-0.1890, w2=0.1910, w3=-0.7260, bias=-0.4125, loss=0.5387
Epoch 14: w1=-0.2317, w2=0.1572, w3=-0.7716, bias=-0.4239, loss=0.5265
Epoch 15: w1=-0.2710, w2=0.1

(-0.9211378798616967, -0.35791543344384996, -0.6138855779539026)

In [ ]:
coef , intercept

(array([[-0.87819064],
        [-0.33768994],
        [-1.1709281 ]], dtype=float32),
 array([-0.58027995], dtype=float32))

####This shows that in the end we were able to come up with same value of w1,w2 and bias using a plain python implementation of gradient descent function